config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  resources :lists
  resources :cart_items
  resources :items
  resources :carts

  post 'populate_cart', to: 'carts#populate'

  patch 'add_cart_item', to: 'cart_items#add'

  devise_for :users

  authenticated :user do
    root 'lists#index', as: :authenticated_root
  end
  
  root 'welcome#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
  delegate :name, to: :item, prefix: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :list_items
  has_many :cart_items
  has_many :carts, through: :cart_items
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :list_items
  has_many :items, through: :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
  belongs_to :item
  delegate :name, to: :item, prefix: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    @cart = Cart.find(params[:cart_item][:cart_id])
    cart_item = CartItem.new(cart_item_params)
    if cart_item.save
      redirect_to @cart, notice: 'Item added'
    end
  end

  def add
    cart_item = CartItem.find(params[:id])
    @cart = cart_item.cart
    if cart_item.update(in_cart: true)
      redirect_to @cart, notice: "Added #{cart_item.item.name}!"
    end
  end


  def destroy
    cart_item = CartItem.find(params[:id])
    @cart = cart_item.cart
    if cart_item.destroy
      redirect_to @cart, notice: "Added #{cart_item.item.name}!"
    end
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:cart_id, :item_id, :quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  # GET /carts
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  def show
    @cart_items = @cart.cart_items.includes(:item).order(in_cart: :asc)
    @items = Item.all
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  def populate
    @list = List.find(params[:list_id])
    @list.list_items.each do |list_item|
      @cart.cart_items.create(
        item: list_item.item,
        quantity: list_item.quantity
      )
    end
    redirect_to @cart, notice: 'Items added'
  end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    redirect_to root_path, notice: 'Cart was successfully destroyed.'
  end

  private

    # Only allow a trusted parameter "white list" through.
    def cart_params
      params[:cart]
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def create
    @list = List.find(params[:list_item][:list_id])
    list_item = ListItem.new(list_item_params)
    if list_item.save
      redirect_to @list, notice: 'Item added'
    end
  end

  private

  def list_item_params
    params.require(:list_item).permit(:list_id, :item_id, :quantity)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to @list, notice: 'List saved'
    else
      flash[:alert] = 'List failed to save'
      render :new
    end
  end

  def show
    @list = List.includes(:items).find(params[:id])
    @items = Item.all
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def filler_text
    FFaker::CheesyLingo.paragraph
  end

  def foundation_key(key)
    {alert: 'alert', notice: 'primary'}[key.to_sym]
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart_items/_form.html.haml
.row
  .large-3.columns
    = simple_form_for cart.cart_items.new do |f|
      = f.hidden_field :cart_id, value: cart.id
      = f.hidden_field :item_id, value: item.id
      = f.input :quantity
      = f.button :submit, 'Add', class: 'tiny radius button'

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @carts.each do |cart|
      %tr
        %td= link_to 'Show', cart
        %td= link_to 'Edit', edit_cart_path(cart)
        %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
%h3 Current cart

.row
  .large-8.columns
    - @cart_items.each do |cart_item|
      .row
        .large-3.columns
          %p{class: "inline smr #{'added-item' if cart_item.in_cart?}"}= "#{cart_item.item_name} - #{cart_item.quantity}"
        .large-6.columns
          - unless cart_item.in_cart?
            = link_to 'Got it!', add_cart_item_path(id: cart_item.id), method: :patch, class: 'tiny radius success button'

  .large-4.columns
    %h4 Add items
    - @items.each do |item|
      %span= item.name 
      = render partial: 'cart_items/form', locals: { cart: @cart, item: item }

    = link_to 'Empty cart', cart_path(@cart), method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny alert button'

app/views/list_items/_form.html.haml
.row
  .large-3.columns
    = simple_form_for list.list_items.new do |f|
      = f.hidden_field :list_id, value: list.id
      = f.hidden_field :item_id, value: item.id
      = f.input :quantity
      = f.button :submit, 'Add', class: 'tiny radius button'

app/views/lists/index.html.haml
.row
  .large-8.columns
    %h3 My lists
    - @lists.each do |list|
      %p= link_to list.name, list_path(list)
      %p= link_to '(add to cart)', populate_cart_path(list_id: list.id), method: :post
      - if session[:cart_id]
        %p= link_to 'View current cart', cart_path(session[:cart_id])
  .large-4.columns
    .new-list
      = link_to 'New list', new_list_path, class: 'tiny secondary button'

app/views/lists/new.html.haml
%h3 New list
= simple_form_for @list do |f|
  = f.input :name
  = f.button :submit

app/views/lists/show.html.haml
%h3= @list.name

.row
  .large-8.columns
    - @list.list_items.each do |list_item|
      %h5= list_item.item_name
      %p
        Quantity:
        = list_item.quantity
  .large-4.columns
  
    %h4 Add items
    - @items.each do |item|
      %span= item.name 
      = render partial: 'list_items/form', locals: { list: @list, item: item }

app/views/welcome/index.html.haml
.row.smt.smb
  .large-12.columns
    %h1.callout.text-center You should sign up for this site!
.row
  .large-4.columns
    = filler_text
  .large-4.columns
    = filler_text
  .large-4.columns
    = filler_text

.row.align-center.smt
  .large-6.large-centered.text-center.columns 
    = link_to 'Sign up', new_user_registration_path, class: 'tiny radius button'
    = link_to 'Sign in', new_user_session_path, class: 'tiny radius button'